### ISSUE TITLE
Supporting partial memory

### ISSUE THREAD

**Issue by lorenzwalthert** [coolbutuseless/memoisetools#1]
Interesting package 👍. For some applications, some parameters are not relevant for the output of the function, because they define *how* the function performs a certain task, not *what* it does. Simple example: A http request. Arguments such as timeout, waiting time between requests etc. does influence the output of the function, but only the behavior at runtime. Would that functionality fit into this package?

**Comment by coolbutuseless** [comment]
That seems useful enough to fit in the actual memoise package.  Could you repeat this issue over there?  i.e. https://github.com/r-lib/memoise

Depending on how hackish the actual implementation is, a PR to memoise would be preferable to memoisetools.

**Comment by lorenzwalthert** [comment]
Done.

**Comment by coolbutuseless** [comment]
Submitted PR https://github.com/r-lib/memoise/pull/75
